# Generated by Django 5.2.4 on 2025-08-08 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_rename_datasetmetadata_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('SUCCESS', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='preprocessed/')),
                ('error_message', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_jobs', to='datasets.metadata')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
