"""
Django settings for ArquitecturaWebBIOCOM project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
import matplotlib
matplotlib.use('Agg')


JWT_ACCESS_TOKEN = config('JWT_ACCESS_TOKEN')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=vt05=lb!lbb!)xp+!a=j$=ph@-m&v1j2x-vot4&btc4o^zco+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

MANUAL_JWT_TOKEN = "" 

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
#    "daphne",
#    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    #API REST para comunicar los servicios
    'rest_framework',
    'rest_framework_simplejwt',
    #Documentacion de la API 
    'corsheaders',
    'drf_spectacular',
    #Servicio de autenticacion
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    #Servicio de Datasets
    'datasets',
    #Procesamiento asincrono
    'preprocessing',
    "django_celery_results",
    "django_celery_beat",
    #Servicio de Analisis
    "analysis",
#    'django_eventstream',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PARSER_CLASSES': [
    'rest_framework.parsers.JSONParser',
    'rest_framework.parsers.FormParser',
    'rest_framework.parsers.MultiPartParser',
    ]
}
from datetime import timedelta

SIMPLE_JWT = {
  'ACCESS_TOKEN_LIFETIME': timedelta(minutes=180),
  'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
  'ROTATE_REFRESH_TOKENS': True,
  'BLACKLIST_AFTER_ROTATION': True,
  'AUTH_HEADER_TYPES': ('Bearer','JWT'),    # prefijos aceptados
  # 'ALGORITHM': 'HS256', 'SIGNING_KEY': SECRET_KEY, …  
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@example.com'

ROOT_URLCONF = 'ArquitecturaWebBIOCOM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
          BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ArquitecturaWebBIOCOM.wsgi.application'
ASGI_APPLICATION = 'ArquitecturaWebBIOCOM.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Ruta absoluta en disco donde se guardarán los archivos subidos
MEDIA_ROOT = BASE_DIR / 'var'

# URL pública para acceder a esos archivos
MEDIA_URL = '/datasets/'

# broker apuntando a varios maestros para failover
CELERY_BROKER_URL = "sentinel://127.0.0.1:26380/0"
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "master_name": "mymaster",
    "sentinels": [
        ("127.0.0.1", 26380),
        ("127.0.0.1", 26381),
        ("127.0.0.1", 26382),
    ],
}

CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False



# Usamos Redis también como backend de resultados si no usas django-db
# CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_TASK_SERIALIZER    = 'json'
CELERY_RESULT_SERIALIZER  = 'json'
CELERY_ACCEPT_CONTENT     = ['json']

# Evitar pérdida de tareas
CELERY_TASK_ACKS_LATE           = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Solo prefetch una tarea a la vez por worker
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Concurrencia basada en CPUs
import multiprocessing
CELERY_WORKER_CONCURRENCY = multiprocessing.cpu_count()

# Timeouts razonables
CELERY_TASK_TIME_LIMIT      = 300
CELERY_TASK_SOFT_TIME_LIMIT = 240

# Canal de capas (Channel Layer)
# Para desarrollo, puedes usar una capa en memoria.
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# configuracion para produccion
#CHANNEL_LAYERS = {
#    "default": {
#        "BACKEND": "channels_redis.core.RedisChannelLayer",
#        "CONFIG": {
#            "master_name": "mymaster",
#            "sentinels": [
#                ("127.0.0.1", 26380),
#                ("127.0.0.1", 26381),
#                ("127.0.0.1", 26382),
#            ],
#        },
#    },
#}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'frontend', 'dist'),
]

CORS_ORIGIN_WHITELIST = (
    'http://localhost:5173',
)


CORS_ALLOWED_ORIGINS = [
  'http://localhost:5173',
]
CORS_ALLOW_CREDENTIALS = True

# Configuración de cookies de sesión/CSRF
CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
