# Generated by Django 5.2.4 on 2025-08-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='storage_path',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='file',
            field=models.FileField(default=1, help_text='Carga el archivo .pt, .joblib, .h5', upload_to='models/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='framework',
            field=models.CharField(choices=[('sklearn', 'scikit-learn'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
