# Generated by Django 5.2.4 on 2025-08-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_mlmodel_storage_path_mlmodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='parameters',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='framework',
            field=models.CharField(choices=[('sklearn', 'scikit-learn'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow'), ('onnx', 'ONNX')], max_length=20),
        ),
    ]
