# Generated by Django 5.2.4 on 2025-08-23 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysisresult_parameters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperparameterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Orden del parámetro (1..n)')),
                ('key_hint', models.CharField(help_text='Nombre sugerido', max_length=100)),
                ('dtype', models.CharField(choices=[('int', 'Entero'), ('float', 'Decimal'), ('str', 'Texto')], default='int', max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hyperparams', to='analysis.mlmodel')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('model', 'position')},
            },
        ),
    ]
