# Generated by Django 5.2.4 on 2025-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_hyperparameterdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='parameters',
            field=models.JSONField(),
        ),
    ]
