# Generated by Django 5.2.4 on 2025-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysisresult_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
