# Generated by Django 5.2.4 on 2025-09-11 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_analysisresult_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeoResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_prediccion', models.IntegerField(help_text='Valor numérico de la predicción (ej. 0, 1, 2).')),
                ('etiqueta_texto', models.CharField(help_text="Texto descriptivo para la predicción (ej. 'Setosa', 'Riesgo Alto').", max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.mlmodel')),
            ],
            options={
                'verbose_name': 'Mapeo de Resultado',
                'verbose_name_plural': 'Mapeos de Resultados',
                'unique_together': {('model', 'valor_prediccion')},
            },
        ),
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Usuario',
                'verbose_name_plural': 'Análisis de Usuarios',
                'unique_together': {('analysis', 'user')},
            },
        ),
    ]
